DROP TABLE track CASCADE;

DROP TABLE album CASCADE;

DROP TABLE album_track CASCADE;

DROP TABLE artist CASCADE;

DROP TABLE artist_album CASCADE;

DROP TABLE artist_track CASCADE;

DROP TABLE playlist CASCADE;

DROP TABLE playlist_track CASCADE;
