name: echo
services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
    image: echo:latest
    ports:
      - '8080:8080'
    volumes:
      - ./server/:app/echo
    networks:
      - shared
    environment:
      - DATABASE_URL=postgres://postgres:postgres@localhost:5432/echo
    depends_on:
      - db
  db:
    image: postgres:17
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    networks:
      - shared
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=echo
networks:
  shared:
volumes:
  db_data:
