/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health_check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_health_check-4972d3280b888a3f65a5cad3fc4aed6d"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/spotify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Generate the spotify authorization url */
        get: operations["get_auth-spotify-dbb9afccfe74d0c7282cb40053eb6e19"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/spotify/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Parse the response after following the authorization url */
        get: operations["get_auth-spotify-callback-171ce3cfe028d54c15e4ce04675b195a"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/current_user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the complete user */
        get: operations["get_v1-current_user-dc0a601424de35d7783927c92f346de9"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/current_user/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a summary of all the current users playlists */
        get: operations["get_v1-current_user-playlists-f218991bbfbd054fbdfeec3bd50a8dac"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CompleteUser */
        CompleteUser: {
            /** Format: int32 */
            id: number;
            name?: string | null;
            spotify: components["schemas"]["PrivateUser"];
            spotify_id: string;
        };
        Image: {
            /** Format: uint32 */
            height?: number | null;
            url: string;
            /** Format: uint32 */
            width?: number | null;
        };
        /** @description Wrapper around  rspotify::PrivateUser */
        PrivateUser: {
            display_name?: string | null;
            email?: string | null;
            href: string;
            id: string;
            images: components["schemas"]["Image"][];
            product?: components["schemas"]["SubscriptionLevel"] | null;
        };
        /** SimplePlaylist */
        SimplePlaylist: {
            collaborative: boolean;
            id: string;
            images: components["schemas"]["Image"][];
            name: string;
            owner_id: string;
            public?: boolean | null;
            /** Format: uint32 */
            total_tracks: number;
        };
        /** SpotifyAuthUrlResponse */
        SpotifyAuthUrlResponse: {
            url: string;
        };
        /** @enum {string} */
        SubscriptionLevel: "Premium" | "Free";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "get_health_check-4972d3280b888a3f65a5cad3fc4aed6d": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    "get_auth-spotify-dbb9afccfe74d0c7282cb40053eb6e19": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpotifyAuthUrlResponse"];
                };
            };
        };
    };
    "get_auth-spotify-callback-171ce3cfe028d54c15e4ce04675b195a": {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    "get_v1-current_user-dc0a601424de35d7783927c92f346de9": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompleteUser"];
                };
            };
        };
    };
    "get_v1-current_user-playlists-f218991bbfbd054fbdfeec3bd50a8dac": {
        parameters: {
            query?: {
                limit?: number | null;
                offset?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimplePlaylist"][];
                };
            };
        };
    };
}
